In [1]:
print("Numpy")

Numpy


## Introduction to Numpy

**numpy.empty**
numpy.empty(shape, dtype=float, order='C', *, device=None, like=None)
Return a new array of given shape and type, without initializing entries.

**Parameters:**
shapeint or tuple of int
Shape of the empty array, e.g., (2, 3) or 2.

dtypedata-type, optional
Desired output data-type for the array, e.g, numpy.int8. Default is numpy.float64.

order{‘C’, ‘F’}, optional, default: ‘C’
Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

**devicestr, optional**
The device on which to place the created array. Default: None. For Array-API interoperability only, so must be "cpu" if passed.

**New in version 2.0.0.**

**likearray_like, optional**
Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

In [1]:
import numpy as np
np.empty([2, 2])

ModuleNotFoundError: No module named 'numpy'

In [ ]:
np.empty([2, 2], dtype=int)

array([[10, 20],
       [30, 40]])

## numpy.eye
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)[source]
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters:
Nint
Number of rows in the output.

Mint, optional
Number of columns in the output. If None, defaults to N.

kint, optional
Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

dtypedata-type, optional
Data-type of the returned array.

order{‘C’, ‘F’}, optional
Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory.

devicestr, optional
The device on which to place the created array. Default: None. For Array-API interoperability only, so must be "cpu" if passed.

In [1]:
import numpy as np
# Creating a NumPy array
arr = np.array([10, 20, 30, 40])
print("Numpy Array:\n",arr)


Numpy Array:
 [10 20 30 40]
Numpy Array with OPeration:
 [15 25 35 45]
Two D Array:
 [[1 2 3]
 [4 5 6]]
Two D Array shape:
 (2, 3)*****

In [2]:
# Performing operations
print("Numpy Array with OPeration:\n",arr + 5)  # Output: [15 25 35 45]
#Multi dimensional arrray
import numpy as np
# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Two D Array:\n",arr)
print("Two D Array shape:\n",arr.shape,end="*****")  # Output: (2, 3)

Numpy Array with OPeration:
 [[ 6  7  8]
 [ 9 10 11]]
Two D Array:
 [[1 2 3]
 [4 5 6]]
Two D Array shape:
 (2, 3)*****